### ISSUE TITLE
how use lapdftext?

### ISSUE THREAD

**Issue by juanbits** [BMKEG/lapdftext#12]
i do a Build Success

and make the jars, but i donw know how use it on my custom project

can u helpme for use it,

for example, i have my pdf documents on "input/" folder and i want extract the text from the pdf and classify the blocks from the pdf (title, abstract, etc)

how can i do this in java?
## example

import dsjfdksjfkds.libratyes

void main (){ 
lapdftext = blockifyClassify("input", rules, "output")
## }

thanks

**Comment by naimavahab** [comment]
Do the output file will be always xml..? Can't we get the title , abstract and other sections separated into a text file.. Do we need to parse the xml..
